configuration: ENC[AES256_GCM,data:V1f6CT8EzDFBPYCDhS0rZDsuKF7+TUH90MXBh5fH3DLii18wA9oCVklRFnUfOVEK4NxL5AXHS6hJiQ8Iim3vO9MMl0DGSV//jgeJrOeaW2eSjRofqNvROKC29U6OJg+ugADUWcr64a+e+U7WgqiVBTlPmkl4pLts26xqieSZ/7Q7TVjXB2UY4CECig69EIWAw+0kJnBXz3Y50NQWUTRJIindKgbbKbUvqzBTqGxSq0xHwT4kcKGvA9++ygkzbmY8NAqc7PhB0EafMwDk6WM4g/aJx7TdZCUUZU8d7yIsAtEj8YzGanImItJUFKIofUAm/bCLclwEkGuKLTT++pGJqKvs8utftrVbtz4CP89B92fnrhhjY6R1uHRYyUolcPB9RIfon8/wjWcq3p9PIbAtH3j+QRtbIf4SQtX9RwQvZraVJk3s48APfy5Bcpb/EzeTWevsivW32WX4pqX1yWUO8mgQPN24oNLLGmZwwpo3m/p/SBJV8kIpQyVjPFYs1aI8AZ945VSHY2jvCmkn7P3rMOnSuOGPiyK2ZR3QsBtW9YVm8OnRwkEYjiSDNcA1KXkKAJW7+bocZ6qgBrmWWBWcn6o428Px9L42+BKhEyTW6I+iyotvRAYxSJLQMKCtvGpCFvS0+EVeS9/UqW4FWEkQExWd26usYtNEvnJnIokdzYeWGODMZMS6/X2+Novz9/Ixnv8Lt033XYeY9Tm7oCBBQBX2NtWkQiUEafyDtXfhB9DGAcsGlp/MpUR6i0mLzTqU/vAhfHS4z4kDU8NirEehZfN/vAIBjlx1w8Tnv28y9hwcHMRI5CR9g7UvvG89zRRJW9+dMIf6bltDX6CevYpXAYFqmKIO63kWggO1V+lHDJrQGhiI2605TVVOquqIg6ty/5LNrWmhRCkTNXLVNb/7d8LolaCe1Ehr8fIufvIWNt10C1NamG04Qq4TKUP5I033tipf3N/XhIrkfJQIxmldlv6K0vvM/QHWVXHhPXV8W7tYb2jUVmHzo5fjiEJQqFc2VY1Hp7mnblQELZmqsiI+FyevRQuZlSoeOWd6C7wSBrN9aNMtjlGOouMhQ1bhaIVp60p42YVX3Vq6vyYKLlyuus9ZNEkOIaGN2ra46cYp2nndiT3mJXOsRLJzVcD9S6dVhrJ5Fo6EQV/X87DQFyGVhVl/9v1L+ocgtXmGW5GJTvd9SigkB0fsrUUiuSj4zXA4FSbB1NxXdS8JaPiN5N1Ey8rhs9BfUHaxR9c58ZkUtJ0SYzDHvRdROvkNNkDDxLJgWBEjZoelJOxb6r7lWOqBm5M+1qpg5gOAi1XMtWmN0isyC5zG+jWfjudfyzXwNGdII2hVr5y+hZ+17KBXyf9OM4A/VvZjmqejcFGoYrkLZEqOZf2BdfhJDITDQO6wgrUJpeHf6a4ZfW3PVhxe4kXYHKvf5EfNL4CHp6LqInsdEYi0eANDmymJ1zxX+TXyizrK8nsgeajGUvn85akIYEKagNFPADdpgoS8vV6Il0sSuodv339udTrjUH9k/owtZzMCwuDrgZovxnhzhvUKDLWGqtXNANjvOXevHFuWGw5I9eY/qJbuW9BJLSdPkqWXv737ShiaWjDjGlMDpAI2FUaPmYHU2Hp46Ue1tjY5FZTCdNIPTkkIiiRK4UGDGO/jB2ai3DSM1Q1QzR6LjuZ/eupJ1myJV/Yhz+glvqieixyF6U3wlA8eQUzZZ2XsqvixbbhrpR5IlW7Gsd7gY97sjC/tjcc0i1T55LkTPTEGo8IsqG9ndbYvrYa2KkUXB4cwiA/fiRbV6CtBY2awhgZh9bMVxBr871T9JEUxBKlxpDWox9vSMxUphXl3HSah+G48dRlv+Zi2WGagCwYwjlNRVZtHxemb0HFqcAY/mhcneYkSl2P8OzftDC+iBw8CKtO6LNaFhXuXc154J2C69R8435uN8JRSIY71SrGR4NOWvCE5e93ByhDgX+tw1uCHqlsntsI902C1K4+cknFDYvqpJIJbhsIo3NZMDRpXwQfVYbGRY9QIqW0DTV5lJlaLM0HfbI2C2M+TnDPdP3MgOn22IqivXJQyE/htK/JalEY/oW3cPS0OFTWG0Po8tbgyiR1NysCr4d9KWP5PzjxKY+PkVf0q5uuLeVNBRaDdHNGF0zpb9O00IPZT2AHT6czVwPWKDJoScreXzagX7YdREArMhMwWmSSL7QszX+2fUDUBxtGetGLt7t3FZIAaVJKAGO/9hDBsxXL0gaJuy6ZkUnoKu1W3WBb9MvofLsmzjvZSOnZqMw0UPh86Zgb9BlQ99twazOijzMKvG324GJBJuCHI33oDElo1rJy3uSRTQ6nsjcyswD02XnhLpw9Y1hz2OzGTP9zta8tUjY/nUKpSjF/a5O/G4myFN3ddlCNcvtgGRZ8e2VTcypqWvNv5BS0txAQGhMbKbSIfoEvRVo8VDk1JjsdkK7muvOyJJQ56Dhke4PD6G/ExqpSVEQmdQjitm8VWMmIDIbSDFm9qSC5mZMTny9Qr+JXGQYZibZk3dP33MmEpsiyxEm0fPsWNJaf3sFLKf8Kuvi/w2o6Gag==,iv:r7mDyCmQ6Yr6zUWU36NC/4RkUTWcvgZbJZJFpDhlo1Y=,tag:41fG9o2IO7l9/cI0DwCgfA==,type:str]
sops:
    age:
        - recipient: age18z96a5v4ugj5lmwgs0xfn4ernq8s44mszf5amp6qxdgyzrg7wusqkhuy8u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZXdIa1ZSemNPNmNIWTV0
            WHhxOW03cVREL2lIYUV5N3BwbUhnMCszWFJNCjJYa0V2eDBFbGlCQVUraCtVakxj
            ZEFQVmFPZkNacjlZdmprODh2OHVKdU0KLS0tIExaV3F6OXE3dEo0dTQ4c2wvNEFh
            dzI2UDdRNjRwVGUySG8xQWtEeGpBcmsKa8/oNYdhIPD6p0lh2iC1WyuaHuYCl6K9
            5Z66j6kHXfWtu533ueAW2aMhnPJzPwXZYh2df+V3/CgeTHCQwnpiOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fido2-hmac1qqpdd5uttx40y0s32yakjkmz5lq2ldf0hzkqy8a0mhwtx8hjqu3pgygp39resz5qh05xt0238d7uwph4c4kz0lcp99tfsl9zgccgm4g9r98z4fdqcngv63uucth4xm84eek4y4tesvyqng7kmf3d37pf3m4p4p3vvwrulc04u0qhup0emzlv2ldqjrc4g8rqz6g4k6zveqlhfeehl5wcp0q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IGZpZG8yLWhtYWMgQUFJIFhOc1FGclZi
            YS9wRmFMRjJwTzdoSjZsalowdkJtQXVMS0ZRL1NhQjh2VG8gQVEgaVVlWUNvQzc2
            R1c5VVR0OXh3YjF4V3duL3dFcFZwaDhva1l3amRVRkdVNCBLcVdneE5ETlI1ekM3
            MU5zOWM1dFVsVjVnd2dKbzliYVl0ajRLWTdxR29Zc1k0ZlA0Zlhqd1g0RitkaSt4
            WDJna1BGVUhHQVdrVnRvVE1nL2RPYzMvUQo3MFh1S0tZcnVMRmMxVm1DcFprSTRF
            M05yZXZNb2FSWFF0d28veWFwRzNjCi0tLSA4TWdkdHFYZHdRRzFhQnVXK0tZQ00r
            NUcwTHBKN3Vjb0dYM0pmWnNhakhRCs9b0MXhye0Xle49MVjS0eROX51WiyJc11po
            Ro9S0x2FlYHbBNOy/U5hgLQSLBJZd/zJgFpTLmfB3uZ0f/GwF7M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fido2-hmac1qqprl2wmagll0ht56zn7d2t7e7ed3a35t3lxhj4m0q575j9s3kmnxqcp39yc4ycvgpsjyddm3a2j6lk3afq2gwdxahpwnag5fv7lfg9lz7l5hyud9s97t8m3220c0khq66n29mau6hel3dmgqfgu9hky3ye4nc4p9zujw80a45l6pzatvq8h4ls9zjvdvnx3nq50p99fr4a5vh4zwgtpm4uq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IGZpZG8yLWhtYWMgQUFJIFNoSmtrSWRT
            aTZWNTBYQzFHY3FGK1h3aXVxUE15dGdYcEVyYlJNb20veDAgQVEgaVVtS2t3eEFZ
            U0kxdTQ5VkxYN1I2a0NrT2FidHd1bjFGRXM5OUtDL0Y3OCBTNU9OTEF2bG4zRlNu
            NGZhNE5hbW91KzgxZlA0dDJnQ1VjTGV4SWt6V2VLaEtMa25IZjJ0UDZDTHEyQVBl
            djRGRkpqV1ROR1lLUENVcVIxN1JsNmljZwpqVW4zdVpEckRFdTVGRm5WOCtkNEN3
            TUR0eFFST2Jmd1Z3QkVIbTY4dVpBCi0tLSBRMkJVbnZtMUNRbzB2WDQ3ZEhqMGpS
            RnpHUUlhd2JZZWF6UE4yMmFMS3RvCvs1mbmpvWT1vO8S4+AOZiUe5zS3Ka/z7L5p
            8VWexg/EJdyFFDT8pxPMAjdFHDD/FXhpI1hxr+vJOjytuoebNTM=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T16:41:51Z"
    mac: ENC[AES256_GCM,data:57l3GDORKlfbge/2YfxJ9OBnbNj48NK3VDXeAP3l7xqYVG6xzwi9J2lKdbXuLGG+YXf8o1DNiJaZWWRUfkFrGRHCTPoivI7+X/bDbCp/sY4L+TaRh41KCovZXmpddQax6Ya9RomzIisepDaM8dHBp44/4Ngjq1B/J0LoBCjX+CQ=,iv:UXv7W5EZOCE1xdoaY37qd4vfqHOZ6yyyDjC6HoPxjXs=,tag:9UiqH6Z7wpxKi9hEvkG60g==,type:str]
    pgp:
        - created_at: "2025-10-22T18:16:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DVVlTbrcXgz8SAQdATiY6pMK7ei3E0JH0E7XvxC4OjmtKPZ+YvEOPY9doJAEw
            hLrPauL+E4EdSuPn/MVMOBZJP4t7WeP5wziNiz2I2tah63dStiFI5vA/bHyHlAS6
            0l4B0dWtATYgndjiqLqXDzLYg70bN3RDl4U+aFsA3hWkSaP5QeQZj9DfoWTKbnEM
            EWcJ650lHKG3Q5zsNAke7/pYqYzdPeLSobZLT52L5QgdXytxNguEjW38ZKGisgaQ
            =koh6
            -----END PGP MESSAGE-----
          fp: 66FF60997B04845FF4C0CB4FEB6FC9F9FC964257
    unencrypted_suffix: _unencrypted
    version: 3.11.0
