configuration: ENC[AES256_GCM,data:QelBo484UVKQ3ixl8kxfj4jG/wSuIfN/4pCt3Zi7lC7P2y+ancaULKVimHT6TSp8OIQWy45dwXmzfWwFVcQvALMAdoPerLYcIB3oHx//Ik6YqXWdh+TJPdq7BOd1dix+aBXCwBcd8ZgYmJfbtmIFhZmDp2bqG4/jin/xhiwpe8aM2cl21LVQfG0G1l04NX4CybZy8CXAW/z9OPqQH8g+e5FAVZvYUQHgTQgjDI6B/Fxd/Hk9z7U+cS/RClGDtd0NYFcOoublvMj4Dj7UbF1OHYgMy8Byvu4Tw1ssCVoN5MHsbCbX56rC8i5BqVLgSNYkIVTc7PuiU3cxSsPJm2ky5Z9Qdzu8djKE3WGE+UCMaS0hwSjqrcIoe2sJNzVJoknR8j3a6YeglOp/FaouuBb80xWuDeDckQCEaCDEDDMhOQKQJ9A9hdfa8NS/47CtcVNNN0R8q3FfayMjfEKkuG1sIHnOmrxAAMIdbnNeUVIS5/td4qGkSn6YFuB0zCg6kBWVBQra0I2iRDik6cr3TarFhZANYwdo3++d1cqxkaMur2ndML3O/Weythu4Rfmujbjd0Zxd38Bgg8Nn/DxLtPU5JuaplTJYXW6G4R3GY8nUdB7aeU35lw1zfXJWMvxJdAZcUuLZTAFTUirOpCADRPVdyt2fKE4/8ulNHZDzuznhg67BvOwvH3NRxumfHYHw0au+oiMhPsZ29uAA2VnD/c9CvAMJvL0TahFALCeiqnHSBsvnGuF8q1q64KJeoIRB/YNZniNpyhqFEpqsQfSQLouulKlp2ElXODoByfVNqhohCD/cZoVY2zsETJDYfnAeOMCJYdyo8Oq5lTJTcMVCHfe+iisZV4IBbqxY2WefvQKmTusTSMfHuMv1LpbV+/YBxBX+Ssz6xVKk5AmzMej98Rezpo7MvDW5yYIWGg+oyuef/MzTZaVyhsiMzpYWJvmNa1Cb3lmkWwsqATLib0olwKETtZiBfzqtwvgjoJgPPWh/DO+UfJzpeTzpZmAFXGVsair2S/1kRc8VH0RCp215scCqNHbkVn5yIQrS0bEd5gs8T4gHS5jHRmqu/ZrY2V5S1/cAOXLsg2QSHguCKKOmmBuw+tq6FoO1AOV2xGm32jQMCZ5ixp54yent7ExdCv/Mft+m6eyCQQpls6QSU5Oa8J2HN4hKX1q9JKDkvxt5OO1rg6dBRq8WsJ3ErkxZUNU=,iv:8nSy1cEDP+EfWlV/Mb48K5tnouPcng/FRLbkOVVZFNA=,tag:koO7cAj8oLxwPmeJGxXVEg==,type:str]
sops:
    age:
        - recipient: age18z96a5v4ugj5lmwgs0xfn4ernq8s44mszf5amp6qxdgyzrg7wusqkhuy8u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN1Y0KzNPaERIZ1NGUElp
            UFpGMXdQbGRpQ25halBkd2VjWnNienJKeVdjCjQzYXkrSG1CbUI4S2pTTWVyK2lI
            STRXSU50NFhpK1NYaGVBSlQ3K2h0TVkKLS0tIGxneHYzcUtzOE1vM3VobHEzS1hF
            UFdrODZBdVF6WmtSb1NkVnAxdmxiQ0kKFc87sZAvS47HBjSGEl1evo3T1hNDxdao
            ytq/NbbI3ytHo2KFcFDSaskS1SXvpHg8V1qaS/gqTaPsM4W9fh9yZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fido2-hmac1qqpdd5uttx40y0s32yakjkmz5lq2ldf0hzkqy8a0mhwtx8hjqu3pgygp39resz5qh05xt0238d7uwph4c4kz0lcp99tfsl9zgccgm4g9r98z4fdqcngv63uucth4xm84eek4y4tesvyqng7kmf3d37pf3m4p4p3vvwrulc04u0qhup0emzlv2ldqjrc4g8rqz6g4k6zveqlhfeehl5wcp0q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IGZpZG8yLWhtYWMgQUFJIGFEWUttQkxG
            ZTNOcWUxemUzRjFpOFU0OWFlS012R2pMTTFFRVJmY0UyaGMgQVEgaVVlWUNvQzc2
            R1c5VVR0OXh3YjF4V3duL3dFcFZwaDhva1l3amRVRkdVNCBLcVdneE5ETlI1ekM3
            MU5zOWM1dFVsVjVnd2dKbzliYVl0ajRLWTdxR29Zc1k0ZlA0Zlhqd1g0RitkaSt4
            WDJna1BGVUhHQVdrVnRvVE1nL2RPYzMvUQpXbzZWdUZpeE1UMW5yK2NlOTlMTUNX
            dmhtaEhQdTRnbjN5amdvdHc0T2R3Ci0tLSAyRTlhSVpYTmhIb2NRdk94Q29zdE1H
            aWRhNFdNalpYMTF4NGxQa1JKcDVNCsivjs9ZqP3uDryrj+78iZUY3I9q7kEXWeSo
            bvh0FEE5ppmEy5OwISv7YVz9jbUqjcqGWpI8LXhTTu6AyjQY/3M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fido2-hmac1qqprl2wmagll0ht56zn7d2t7e7ed3a35t3lxhj4m0q575j9s3kmnxqcp39yc4ycvgpsjyddm3a2j6lk3afq2gwdxahpwnag5fv7lfg9lz7l5hyud9s97t8m3220c0khq66n29mau6hel3dmgqfgu9hky3ye4nc4p9zujw80a45l6pzatvq8h4ls9zjvdvnx3nq50p99fr4a5vh4zwgtpm4uq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IGZpZG8yLWhtYWMgQUFJIDZZNzB4c01L
            S2dsY3NjNWlCS2NMRXhIdkQramNEUkFaZW03NmY3RjlLaWsgQVEgaVVtS2t3eEFZ
            U0kxdTQ5VkxYN1I2a0NrT2FidHd1bjFGRXM5OUtDL0Y3OCBTNU9OTEF2bG4zRlNu
            NGZhNE5hbW91KzgxZlA0dDJnQ1VjTGV4SWt6V2VLaEtMa25IZjJ0UDZDTHEyQVBl
            djRGRkpqV1ROR1lLUENVcVIxN1JsNmljZwoxanhkc01aZlN6ZXR1dnhabDd0RVFB
            OCsrRjVjemRHM3cxZHoxdGRVNDhVCi0tLSBzY0R1WHFvb3FvVTNqdEt1cUQ0eG1i
            RDZGTzl5YlNRTFRGdnVHYUtNdzJFChPEOmKfWyqiiIaqv1mkN494xrwAB0aFEVL5
            gKKLBWvh/TIpWl6Jhl65RV1cXHyrtyQMmxdBo+QfNrFcgDzWNI8=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T05:15:15Z"
    mac: ENC[AES256_GCM,data:TfPlkWZ5frYMP7aOn5QJ3vnhnjGHCyV1bO8IhTfvzMRJiQvCYNXJxmFCa5Qgg9pyMlg8cCo2jHFQnqIrhib4yRCoybLyoAjMahAwG9ujUavxXjPIXzMH3Tg2eyVG1FMf8kBRdZRd92nHj2WRCqeQqr9ui0tu3o1nQX9hwtFrsis=,iv:Xys7bASN7DDjfhf37N56NiPOem0lfGvzXPGTVR9nrdM=,tag:oO1DtrEU6XPHgDpkSNar7A==,type:str]
    pgp:
        - created_at: "2025-10-30T05:15:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DVVlTbrcXgz8SAQdAJRJEbqSgvGVnxPaYp0YkYBIRvBUIUImmFpyt4Sb36n8w
            5iM+GXDWp4aALhqvHpK1aZX2LJYsAYen/jyjEK/uUdbpesCBQwEsAYFk+sFVg3rh
            0l4Bfkhzm8wH4k+3TZ2lWJZesyumFkT8eRPWTCFfR76BbXA1waIs8Sk8dCRGA1gs
            V9Mop6ljdbDdbx/5VtJrMIoi1AAg4CyRqjIZ4Xlgey8aSkEUhDLjTAzX0Ib5ix1U
            =8C/O
            -----END PGP MESSAGE-----
          fp: 66FF60997B04845FF4C0CB4FEB6FC9F9FC964257
    unencrypted_suffix: _unencrypted
    version: 3.11.0
